### ISSUE TITLE
`KeyError` in feature parsing

### ISSUE THREAD

**Issue by AlexVanMechelen** [packing-box/docker-packing-box#126]
### Issue
`exe.data` results in a `KeyError`

### Reproduce
```
exe = Executable("/mnt/share/dataset-packed-pe/packed/ASPack/aspack_ntfsinfo.exe")
Features.source = "research-yaml-confs/features.yml"
exe.features
exe.data
```

### Traceback
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/pbox/core/executable/__init__.py", line 254, in data
    return Features(self)
           ^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/pbox/core/executable/features.py", line 135, in __init__
    d.update({c: globals()[c] for c in FEATURE_CONSTANTS})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/pbox/core/executable/features.py", line 135, in <dictcomp>
    d.update({c: globals()[c] for c in FEATURE_CONSTANTS})
                 ~~~~~~~~~^^^
KeyError: 'IMPORT_SUFFIXES'
```

**Comment by dhondta** [comment]
Fixed with PR #127.
