### ISSUE TITLE
Bug pbox-update

### ISSUE THREAD

**Issue by jramhani** [packing-box/docker-packing-box#140]
`$ pbox-update`

```bash 
Copying files from packing-box...
Upgrading Pip...
Upgrading pbox library...
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.7.1 requires platformdirs<4.0.0,>=3.0.0, but you have platformdirs 4.2.0 which is incompatible.
Regenerating Bash completions...
/home/user/.local/lib/python3.11/site-packages/_distutils_hack/__init__.py:55: UserWarning: Reliance on distutils from stdlib is deprecated. Users must rely on setuptools to provide the distutils module. Avoid importing distutils or import setuptools first, and avoid setting SETUPTOOLS_USE_DISTUTILS=stdlib. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(

```

**Comment by dhondta** [comment]
Did you retry `pbox-update` ?
Did you try `pip-install --upgrade pip` ?

**Comment by jramhani** [comment]
The error is not showing anymore ... But the warning is still there  (and is showing for many/every command) : 

`$ pbox-update`
```bash 
Copying files from packing-box...
Upgrading Pip...
Upgrading pbox library...
Regenerating Bash completions...
/home/user/.local/lib/python3.11/site-packages/_distutils_hack/__init__.py:55: UserWarning: Reliance on distutils from stdlib is deprecated. Users must rely on setuptools to provide the distutils module. Avoid importing distutils or import setuptools first, and avoid setting SETUPTOOLS_USE_DISTUTILS=stdlib. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(

```

- Example :

`$ executable plot <exec-file>`

```bash
/home/user/.local/lib/python3.11/site-packages/_distutils_hack/__init__.py:55: UserWarning: Reliance on distutils from stdlib is deprecated. Users must rely on setuptools to provide the distutils module. Avoid importing distutils or import setuptools first, and avoid setting SETUPTOOLS_USE_DISTUTILS=stdlib. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(
Traceback (most recent call last):
  File "/home/user/.opt/tools/executable", line 48, in <module>
    getattr(Executable(args.executable), args.command)(**vars(args))
  File "/home/user/.local/lib/python3.11/site-packages/pbox/core/executable/__init__.py", line 187, in plot
    path = figure_path(fn, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/pbox/helpers/figure.py", line 55, in figure_path
    filename = f"{p.dirname.joinpath(p.stem)}.{format or config['format']}"
                                                         ~~~~~~^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/pbox/helpers/config.py", line 69, in __getitem__
    return self.get(option, error=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/pbox/helpers/config.py", line 197, in get
    raise KeyError(option)
KeyError: 'format'
```

**Comment by dhondta** [comment]
@jramhani The issue with `executable` is a separate one. This is due to a change in the config key for the image format to generate figures. The key shall be `img_format` instead of `format` for now.
