### ISSUE TITLE
ERROR: dataset plot features (true_class: NoneType object is not subscriptable)

### ISSUE THREAD

**Issue by jramhani** [packing-box/docker-packing-box#142]
`dataset plot features fileless_dataset_mixed number_wx_sections`

```bash
00:00:01.451 [INFO] Preparing plot data...
00:00:01.455 [INFO] Counting values for feature number_wx_sections...
Traceback (most recent call last):
  File "/home/user/.opt/tools/dataset", line 215, in <module>
    getattr(ds, args.command)(**vars(args))
  File "/home/user/.local/lib/python3.12/site-packages/pbox/core/dataset/__init__.py", line 696, in plot
    _PLOTS[subcommand](self, **kw)
  File "/home/user/.local/lib/python3.12/site-packages/pbox/helpers/figure.py", line 67, in _wrapper
    imgs = f(*a, **configure_style(**kw))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.12/site-packages/pbox/core/dataset/visualization.py", line 72, in _features_bar_chart
    true_class_cap = true_class[0].upper() + true_class[1:]
                     ~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by dhondta** [comment]
Fixed by 6bdb3a73de6fada620862abad78735cf46bb686a
