### ISSUE TITLE
`PermissionError` when creating ELF dataset 

### ISSUE THREAD

**Issue by smarbal** [packing-box/docker-packing-box#16]
Creating an ELF dataset produces this output : 
```
dataset -v make elf-upx-dataset -f ELF -a -p upx -n 40
00:00:03.420 [INFO    ] dataset            - Source directories: /sbin,/usr/bin
00:00:03.420 [INFO    ] dataset            - Considered formats: ELF
00:00:03.420 [INFO    ] dataset            - Selected packers:   UPX
00:00:03.420 [INFO    ] dataset            - Searching for executables...
Traceback (most recent call last):
  File "/home/user/.opt/tools/dataset", line 149, in <module>
    getattr(ds, args.command)(**vars(args))
  File "/home/user/.local/lib/python3.10/site-packages/pbox/common/utils.py", line 150, in _wrapper
    return f(s, *a, **kw)
  File "/home/user/.local/lib/python3.10/site-packages/pbox/common/dataset.py", line 403, in make
    for exe in self._walk(n <= 0):
  File "/home/user/.local/lib/python3.10/site-packages/pbox/common/dataset.py", line 251, in _walk
    for exe in ts.Path(src, expand=True).walk(filter_func=lambda x: x.is_file(), sort=False):
  File "/home/user/.local/lib/python3.10/site-packages/tinyscript/helpers/path.py", line 303, in walk
    for item in self.listdir(lambda p: not p.is_dir(), sort):
  File "/home/user/.local/lib/python3.10/site-packages/tinyscript/helpers/path.py", line 266, in listdir
    if filter_func(item):
  File "/home/user/.local/lib/python3.10/site-packages/tinyscript/helpers/path.py", line 303, in <lambda>
    for item in self.listdir(lambda p: not p.is_dir(), sort):
  File "/home/user/.local/lib/python3.10/site-packages/pathlib2/__init__.py", line 1733, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "/home/user/.local/lib/python3.10/site-packages/pathlib2/__init__.py", line 1523, in stat
    return self._accessor.stat(self)
  File "/home/user/.local/lib/python3.10/site-packages/pathlib2/__init__.py", line 646, in wrapped
    return strfunc(str(pathobj), *args)
PermissionError: [Errno 13] Permission denied: '/usr/bin/dotnet'

```

**Comment by dhondta** [comment]
Hi @smarbal 
Due to the fixed install of `dotnet`, this issue shall now be fixed.
