### ISSUE TITLE
`KeyError` while using `model train` with PE

### ISSUE THREAD

**Issue by smarbal** [packing-box/docker-packing-box#7]
Using the `model train` command on a dataset composed of PE, this error occurs (for any algorithm): 
```
# model train my-dataset -a kmeans
00:00:02.057 [INFO] Selected algorithm: K-Means clustering
00:00:02.058 [INFO] Reference dataset:  my-dataset(PE32,PE64)
00:00:02.059 [INFO] Computing features...
00:00:05.566 [WARNING] Bad expression: checksum == 0
00:00:05.566 [ERROR] name 'checksum' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pbox/learning/features/__init__.py", line 111, in __init__
    self[n] = feature(d)
  File "/usr/local/lib/python3.8/dist-packages/pbox/common/utils.py", line 66, in __call__
    e = eval2(self.result, d, {}, whitelist_nodes=WL_NODES + WL_EXTRA_NODES)
  File "/usr/local/lib/python3.8/dist-packages/tinyscript/helpers/expressions.py", line 125, in eval2
    return __eval(expression, globals, locals, blacklist_builtins, whitelist_nodes)
  File "/usr/local/lib/python3.8/dist-packages/tinyscript/helpers/expressions.py", line 54, in __eval
    raise UnknownNameError("name '%s' is not defined" % node.id)
UnknownNameError: name 'checksum' is not defined
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/tools/model", line 117, in <module>
    getattr(m, args.command)(**vars(args))
  File "/usr/local/lib/python3.8/dist-packages/pbox/learning/model.py", line 521, in train
    if not self._prepare(**kw):
  File "/usr/local/lib/python3.8/dist-packages/pbox/learning/model.py", line 220, in _prepare
    __parse(ds.files.listdir(is_executable), False)
  File "/usr/local/lib/python3.8/dist-packages/pbox/learning/model.py", line 204, in __parse
    self._data = self._data.append(exe.data, ignore_index=True)
  File "/usr/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/pbox/learning/executable.py", line 28, in data
    return Features(self)
  File "/usr/local/lib/python3.8/dist-packages/tinyscript/preimports/log.py", line 91, in _wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pbox/learning/features/__init__.py", line 120, in __init__
    todo.appendleft(Features.registry[exe.format][name2])
KeyError: 'checksum'
```

**Comment by dhondta** [comment]
Hi @smarbal 
From within the Docker image, please `pbox-update` and retry your command.
The issue may come from an outdated version of the `pbox` package.

**Comment by dhondta** [comment]
Hi @smarbal 
I found a situation in which the error you mentioned may occur with a dataset of ELF files. Are you sure you did not mix both errors (see other error split in #8 ) ?

**Comment by smarbal** [comment]
Hi @dhondta,
pbox is up-to-date. 
I've checked and the issue happens well with PE files. 
I've made sure to make a new dataset just to be sure and it shows a new error. 
Dataset : 
 `PE-test-dataset  40            14MB  yes    PE32,PE64  {23},upx{4},upx-3.92{3},upx-3.91{2},upx-3.93{2},upx-3.94{2},mpress{1}...`

Traceback : 
```
model train PE-test-dataset -a kmeans
00:00:02.743 [INFO] Selected algorithm: K-Means clustering
00:00:02.744 [INFO] Reference dataset:  PE-test-dataset(PE32,PE64)
00:00:02.745 [INFO] Computing features...
00:00:03.989 [WARNING] Bad expression: base_of_code % 0x1000 == 0
00:00:03.990 [ERROR] name 'base_of_code' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pbox/learning/features/__init__.py", line 111, in __init__
    self[n] = feature(d)
  File "/usr/local/lib/python3.8/dist-packages/pbox/common/utils.py", line 66, in __call__
    e = eval2(self.result, d, {}, whitelist_nodes=WL_NODES + WL_EXTRA_NODES)
  File "/usr/local/lib/python3.8/dist-packages/tinyscript/helpers/expressions.py", line 125, in eval2
    return __eval(expression, globals, locals, blacklist_builtins, whitelist_nodes)
  File "/usr/local/lib/python3.8/dist-packages/tinyscript/helpers/expressions.py", line 54, in __eval
    raise UnknownNameError("name '%s' is not defined" % node.id)
UnknownNameError: name 'base_of_code' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/tools/model", line 117, in <module>
    getattr(m, args.command)(**vars(args))
  File "/usr/local/lib/python3.8/dist-packages/pbox/learning/model.py", line 521, in train
    if not self._prepare(**kw):
  File "/usr/local/lib/python3.8/dist-packages/pbox/learning/model.py", line 220, in _prepare
    __parse(ds.files.listdir(is_executable), False)
  File "/usr/local/lib/python3.8/dist-packages/pbox/learning/model.py", line 204, in __parse
    self._data = self._data.append(exe.data, ignore_index=True)
  File "/usr/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/pbox/learning/executable.py", line 28, in data
    return Features(self)
  File "/usr/local/lib/python3.8/dist-packages/tinyscript/preimports/log.py", line 91, in _wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pbox/learning/features/__init__.py", line 131, in __init__
    if not bad and counts[n] > 10:
KeyError: 'is_base_of_code_standard'
```

**Comment by dhondta** [comment]
@smarbal 
Could you recheck if you still get this error ?

**Comment by smarbal** [comment]
@dhondta Seems good here. Couldn't reproduce the error in similar conditions.
