### ISSUE TITLE
`pbox.common.modifiers` not found

### ISSUE THREAD

**Issue by rjzak** [packing-box/docker-packing-box#78]
```
┌──[user@packing-box]──[/mnt/share]──[✘ 1]────────                                                                                                                                                               ────[172.17.0.2]──[14:36:44]────
$ file hello.x86.exe 
hello.x86.exe: PE32 executable (console) Intel 80386, for MS Windows, 7 sections

┌──[user@packing-box]──[/mnt/share]────────                                                                                                                                                                      ────[172.17.0.2]──[14:42:24]────
$ packing-box test packer upx
00:00:00.617 [INFO] Testing UPX...
00:00:00.619 [INFO] ELF32
00:00:02.218 [SUCCESS] perl
00:00:02.259 [FAILURE] wine
00:00:02.745 [SUCCESS] wineserver32
00:00:02.752 [INFO] ELF64
00:00:02.810 [SUCCESS] cat
00:00:02.939 [SUCCESS] ls
00:00:02.044 [SUCCESS] mandb
00:00:03.259 [SUCCESS] ssh-keysign
00:00:06.124 [SUCCESS] git
00:00:06.138 [INFO] MSDOS
00:00:06.169 [INFO] PE32
00:00:06.374 [SUCCESS] winhlp32.exe
00:00:06.468 [SUCCESS] plugplay.exe
00:00:06.614 [SUCCESS] winemine.exe
00:00:06.719 [SUCCESS] twain_32.dll
00:00:06.916 [SUCCESS] msscript.ocx
00:00:06.033 [SUCCESS] msgsm32.acm
00:00:06.036 [INFO] PE64
00:00:07.125 [SUCCESS] hh.exe
00:00:07.214 [SUCCESS] spoolsv.exe
00:00:07.425 [SUCCESS] dmscript.dll
00:00:07.671 [SUCCESS] msscript.ocx
00:00:07.753 [SUCCESS] msadp32.acm

┌──[user@packing-box]──[/mnt/share]────────                                                                                                                                                                      ────[172.17.0.2]──[14:43:29]────
$ packer --help
Traceback (most recent call last):
  File "/home/user/.opt/tools/packer", line 6, in <module>
    from pbox.common.modifiers import Modifiers
ModuleNotFoundError: No module named 'pbox.common.modifiers'

┌──[user@packing-box]──[/mnt/share]────────                                                                                                                                                                      ────[172.17.0.2]──[14:36:26]────
$ packer upx hello.x86.exe --prefix "upx_"
Traceback (most recent call last):
  File "/home/user/.opt/tools/packer", line 6, in <module>
    from pbox.common.modifiers import Modifiers
ModuleNotFoundError: No module named 'pbox.common.modifiers'
```

On the latest commit, 9b95886, the Python module `pbox` seems to have an issue.

**Comment by dhondta** [comment]
@rjzak Thanks for bringing this to my attention !
I modified the nomenclature from _modifiers_ to _alterations_ with the following ideas : 
- _alterations_ are sets of operations that may combine multiple _modifiers_
- _modifiers are single building blocks that modify a binary in a precise way
While I moved `pbox.common.modifiers` to `pbox.common.alterations`, I forgot multiple references elsewhere in the code. This is now fixed.
