### ISSUE TITLE
ERROR: dataset show 

### ISSUE THREAD

**Issue by jramhani** [packing-box/docker-packing-box#86]
## Command used
`dataset show upx`

## Error traceback
```bash
Traceback (most recent call last):
  File "/home/user/.opt/tools/dataset", line 208, in <module>
    getattr(ds, args.command)(**vars(args))
  File "/home/user/.local/lib/python3.11/site-packages/pbox/core/dataset/__init__.py", line 777, in show
    r.extend(self.overview)
             ^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/pbox/core/dataset/__init__.py", line 976, in overview
    i, p = _shorten(e.realpath)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/pbox/core/dataset/__init__.py", line 950, in _shorten
    return i, str(p.relative_to(s))
                  ^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/pathlib2/__init__.py", line 1217, in relative_to
    raise ValueError("{0!r} does not start with {1!r}"
ValueError: '/mnt/share/dataset-packed-pe/packed/UPX/upx_Autoruns.exe' does not start with 'dataset-packed-pe/packed/UPX'
```

**Comment by jramhani** [comment]
## List of my datasets
`dataset list`

## Result
```bash
Datasets (28)
                                                                                           
         Name          #Executables   Size    Files    Formats            Packers          
 ───────────────────────────────────────────────────────────────────────────────────────── 
      
  upx                  123            36MB    yes     PE32        upx{122},exe32pack{1}    
  upx_fileless         123            145KB   no      PE32        upx{122},exe32pack{1}    
  ```
