### ISSUE TITLE
Issue when building

### ISSUE THREAD

**Issue by jramhani** [packing-box/docker-packing-box#88]
When building

```bash
 => ERROR [framework 10/17] RUN find /tmp/analyzers -type f -executable -  1.0s
------
 > [framework 10/17] RUN find /tmp/analyzers -type f -executable -exec mv {} /home/user/.opt/bin/ ;  && /home/user/.opt/tools/packing-box setup analyzer:
0.912 Traceback (most recent call last):
0.912   File "/home/user/.opt/tools/packing-box", line 3, in <module>
0.913     from pbox import *
0.913   File "/home/user/.local/lib/python3.11/site-packages/pbox/__init__.py", line 5, in <module>
0.913     from .core import *
0.913   File "/home/user/.local/lib/python3.11/site-packages/pbox/core/__init__.py", line 6, in <module>
0.913     from .dataset import *
0.913   File "/home/user/.local/lib/python3.11/site-packages/pbox/core/dataset/__init__.py", line 6, in <module>
0.913     from .visualization import *
0.913   File "/home/user/.local/lib/python3.11/site-packages/pbox/core/dataset/visualization.py", line 5, in <module>
0.913     from ..executable import Executable
0.913   File "/home/user/.local/lib/python3.11/site-packages/pbox/core/executable/__init__.py", line 2, in <module>
0.913     from bintropy import entropy
0.913   File "/home/user/.local/lib/python3.11/site-packages/bintropy/__init__.py", line 68, in <module>
0.913     lief.EXE_FORMATS.PE: (6.677, 7.199),
0.913     ^^^^^^^^^^^^^^^^
0.913 AttributeError: module 'lief' has no attribute 'EXE_FORMATS'
------
Dockerfile:169
--------------------
 168 |     COPY --chown=$USER $FILES/analyzers/* /tmp/analyzers/
 169 | >>> RUN find /tmp/analyzers -type f -executable -exec mv {} $UOPT/bin/ \; \
 170 | >>>  && $PBOX setup analyzer
 171 |     # install detectors (including wrapper scripts)
--------------------
ERROR: failed to solve: process "/bin/sh -c find /tmp/analyzers -type f -executable -exec mv {} $UOPT/bin/ \\;  && $PBOX setup analyzer" did not complete successfully: exit code: 1
```

**Comment by dhondta** [comment]
@jramhani Please attempt a build again and provide feedback.

**Comment by dhondta** [comment]
@jramhani  Just got the same issue. This is due to an API change from LIEF 0.14.0 (previous version was 0.13.0). I will fix this ASAP.
